# Generated by Django 3.1.4 on 2020-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_quote', to='my_app.User'),
        ),
    ]
