# Generated by Django 3.1.4 on 2020-12-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20201220_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_uploaded', to='my_app.user'),
        ),
    ]
